### **`Backward propogation using Keras`**

In [14]:
import numpy as np
import pandas as pd

In [15]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], 
                  columns=['cgpa', 'profile_score', 'lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [16]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 

In [17]:
model = Sequential()

model.add(Dense(2, activation='linear', input_dim=2))
model.add(Dense(1, activation='linear'))

model.summary()

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [18]:
model.get_weights()

[array([[ 0.45770657,  0.50811815],
        [-0.51940924, -0.13396227]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[-1.0164127 ],
        [ 0.67056906]], dtype=float32),
 array([0.], dtype=float32)]

In [19]:
new_weights = [np.array([[ 0.1,  0.1 ],[0.1,  0.1 ]], dtype=float),
        np.array([0., 0.], dtype=float),
        np.array([[0.1],[0.1]], dtype=float),
        np.array([0.], dtype=float)]

In [20]:
model.set_weights(new_weights)

In [21]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [22]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [24]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=80, verbose=1, batch_size=1)

Epoch 1/80


4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4313 
Epoch 2/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - loss: 1.4130 
Epoch 3/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.3510 
Epoch 4/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - loss: 1.3186 
Epoch 5/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step - loss: 1.2945
Epoch 6/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2515     
Epoch 7/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - loss: 1.2480
Epoch 8/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.2007 
Epoch 9/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1925 
Epoch 10/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1609 
Epoch 11/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1432 
Epoch 12/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1296 
Epoch 13/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1371 
Epoch 14/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 1.1077 
Epoch 15/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 1.1003 
Epoch 16/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6

In [25]:
model.get_weights()

[array([[0.35932875, 0.35932875],
        [0.41220662, 0.41220662]], dtype=float32),
 array([0.29382053, 0.29382053], dtype=float32),
 array([[0.39869118],
        [0.39869118]], dtype=float32),
 array([0.2166803], dtype=float32)]