### **`Backpropogation In classification problem manually`**

In [60]:
import numpy as np
import pandas as pd

In [61]:
df = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]], columns=['cgpa', 'profile_score', 'placed'])

In [62]:
df

cgpa  profile_score  placed
0     8              8       1
1     7              9       1
2     6             10       0
3     5              5       0

In [63]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for l in range(1,L):
        parameters['W'+str(l)] = np.ones((layer_dims[l-1], layer_dims[1])) * 0.1
        parameters['b'+str(l)] = np.zeros((layer_dims[1],1))

    return parameters

`utility Function`

In [64]:
def sigmoid(Z):
    A = 1/(1+np.exp(-Z))
    return A

In [65]:
def linear_forward(A_prev, W, b):
    Z = np.dot(W.T, A_prev) + b
    A = sigmoid(Z)
    return A

Forward Propagation

In [66]:
# L-layer feed forward

def L_layer_forward(X, parameters):

  A = X
  L = len(parameters) // 2                  # number of layers in the neural network
  
  for l in range(1, L+1):
    A_prev = A 
    Wl = parameters['W' + str(l)]
    bl = parameters['b' + str(l)]
    # print("A"+str(l-1)+": ", A_prev)
    # print("W"+str(l)+": ", Wl)
    # print("b"+str(l)+": ", bl)
    print("--"*20)

    A = linear_forward(A_prev, Wl, bl)
    # print("A"+str(l)+": ", A)
    # print("**"*20)
          
  return A,A_prev

In [67]:
def update_parameters(parameters,y,y_hat,A1,X):
  parameters['W2'][0][0] = parameters['W2'][0][0] + (0.0001 * (y - y_hat)*A1[0][0])
  parameters['W2'][1][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat)*A1[1][0])
  parameters['b2'][0][0] = parameters['W2'][1][0] + (0.0001 * (y - y_hat))

  parameters['W1'][0][0] = parameters['W1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
  parameters['W1'][0][1] = parameters['W1'][0][1] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
  parameters['b1'][0][0] = parameters['b1'][0][0] + (0.0001 * (y - y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))

  parameters['W1'][1][0] = parameters['W1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
  parameters['W1'][1][1] = parameters['W1'][1][1] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
  parameters['b1'][1][0] = parameters['b1'][1][0] + (0.0001 * (y - y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [68]:
X = df[['cgpa', 'profile_score']].values[0].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[0][0]

# Parameter initialization
parameters = initialize_parameters([2,2,1])

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

----------------------------------------
----------------------------------------
Loss for this student -  0.613402628898913


{'W1': array([[0.10000513, 0.10000513],
        [0.10000513, 0.10000513]]),
 'b1': array([[6.41054186e-07],
        [6.41054186e-07]]),
 'W2': array([[0.10003815, 0.1       ],
        [0.10003815, 0.1       ]]),
 'b2': array([[0.100084],
        [0.      ]])}

In [69]:
X = df[['cgpa', 'profile_score']].values[1].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[1][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

----------------------------------------
----------------------------------------
Loss for this student -  0.568725622654268


{'W1': array([[0.10000937, 0.10001059],
        [0.10000937, 0.10001059]]),
 'b1': array([[1.24770113e-06],
        [1.24770113e-06]]),
 'W2': array([[0.10007424, 0.1       ],
        [0.10007424, 0.1       ]]),
 'b2': array([[0.10011761],
        [0.        ]])}

In [70]:
X = df[['cgpa', 'profile_score']].values[2].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[2][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

----------------------------------------
----------------------------------------
Loss for this student -  0.8353333695154365


{'W1': array([[0.10000463, 0.10000267],
        [0.10000463, 0.10000267]]),
 'b1': array([[4.56125378e-07],
        [4.56135584e-07]]),
 'W2': array([[0.10002712, 0.1       ],
        [0.10002712, 0.1       ]]),
 'b2': array([[0.09997049],
        [0.        ]])}

In [71]:
X = df[['cgpa', 'profile_score']].values[3].reshape(2,1) # Shape(no of features, no. of training example)
y = df[['placed']].values[3][0]

y_hat,A1 = L_layer_forward(X,parameters)
y_hat = y_hat[0][0]

update_parameters(parameters,y,y_hat,A1,X)

print('Loss for this student - ',-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

parameters

----------------------------------------
----------------------------------------
Loss for this student -  0.8238180133031612


{'W1': array([[0.09999911, 0.09999716],
        [0.09999911, 0.09999716]]),
 'b1': array([[-6.47175329e-07],
        [-6.47175081e-07]]),
 'W2': array([[0.09998609, 0.1       ],
        [0.09998609, 0.1       ]]),
 'b2': array([[0.09992997],
        [0.        ]])}

Epochs implementation

In [72]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 50

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) # Shape(no of features, no. of training example)
    y = df[['placed']].values[j][0]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat) - (1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
Epoch -  1 Loss -  0.7103199085929446
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
Epoch -  2 Loss -  0.6991702892802629
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------------------------
----------------------

{'W1': array([[0.09994267, 0.09984548],
        [0.09994272, 0.09984548]]),
 'b1': array([[-3.38405750e-05],
        [-3.38419977e-05]]),
 'W2': array([[0.09920806, 0.1       ],
        [0.09920816, 0.1       ]]),
 'b2': array([[0.09915209],
        [0.        ]])}

In [73]:
import numpy as np
import pandas as pd

In [74]:
df = pd.DataFrame([[8,8,4], [7,9,5], [6,10,6], [5,12,7]], 
                  columns=['cgpa', 'profile_score', 'lpa'])
df

cgpa  profile_score  lpa
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [75]:
import tensorflow
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense 

model = Sequential()

model.add(Dense(2, activation='relu', input_dim=2))
model.add(Dense(1, activation='sigmoid'))

model.summary()

c:\Users\Lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\keras\src\layers\core\dense.py:92: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [76]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)
model.compile(loss='mean_squared_error', optimizer=optimizer)

In [77]:
model.fit(df.iloc[:,0:-1].values, df['lpa'].values, epochs=80, verbose=1, batch_size=1)

Epoch 1/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 6ms/step - loss: 26.2468  
Epoch 2/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.2364 
Epoch 3/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.2265 
Epoch 4/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.2177 
Epoch 5/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.2070 
Epoch 6/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1982 
Epoch 7/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1881 
Epoch 8/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1784 
Epoch 9/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1680 
Epoch 10/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1592 
Epoch 11/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1487 
Epoch 12/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1395 
Epoch 13/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1292 
Epoch 14/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - loss: 26.1204 
Epoch 15/80
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - loss: 26.1097 
Epoch 16/80
4/4 ━━

In [78]:
model.get_weights()

[array([[ 0.15632999, -0.5944707 ],
        [-1.1873213 , -0.50808805]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.4082334],
        [1.200787 ]], dtype=float32),
 array([0.30983365], dtype=float32)]